name: JobList365 - DuckDuckGo Scraper Update

on:
  workflow_dispatch:  # manual trigger from Actions
  schedule:
    - cron: '0 19 * * *'  # daily at 00:30 IST (19:00 UTC previous day)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run DuckDuckGo scraper
        run: |
          python scripts/duck_scraper.py

      - name: Commit & push updated CSV (if changed)
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add data/Joblist365_data_duckduck_updated.csv || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update DuckDuckGo results (website/linkedin/roles) [ci skip]" || true
            git push
          fi
